// Code generated by "stringer -type=Op -trimprefix=Op"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInvalid-0]
	_ = x[OpLoadScalarConst-1]
	_ = x[OpLoadStrConst-2]
	_ = x[OpMove-3]
	_ = x[OpMove8-4]
	_ = x[OpMoveResult2-5]
	_ = x[OpNot-6]
	_ = x[OpIsNil-7]
	_ = x[OpIsNotNil-8]
	_ = x[OpIsNilInterface-9]
	_ = x[OpIsNotNilInterface-10]
	_ = x[OpLen-11]
	_ = x[OpCap-12]
	_ = x[OpStrSlice-13]
	_ = x[OpStrSliceFrom-14]
	_ = x[OpStrSliceTo-15]
	_ = x[OpStrIndex-16]
	_ = x[OpSliceIndexScalar8-17]
	_ = x[OpSliceIndexScalar64-18]
	_ = x[OpSliceSetScalar8-19]
	_ = x[OpSliceSetScalar64-20]
	_ = x[OpConcat-21]
	_ = x[OpStrEq-22]
	_ = x[OpStrNotEq-23]
	_ = x[OpIntNeg-24]
	_ = x[OpScalarEq-25]
	_ = x[OpScalarNotEq-26]
	_ = x[OpIntGt-27]
	_ = x[OpIntGtEq-28]
	_ = x[OpIntLt-29]
	_ = x[OpIntLtEq-30]
	_ = x[OpIntAdd-31]
	_ = x[OpIntSub-32]
	_ = x[OpIntXor-33]
	_ = x[OpIntMul-34]
	_ = x[OpIntDiv-35]
	_ = x[OpIntInc-36]
	_ = x[OpIntDec-37]
	_ = x[OpJump-38]
	_ = x[OpJumpZero-39]
	_ = x[OpJumpNotZero-40]
	_ = x[OpCall-41]
	_ = x[OpCallRecur-42]
	_ = x[OpCallVoid-43]
	_ = x[OpCallNative-44]
	_ = x[OpCallVoidNative-45]
	_ = x[OpPushVariadicBoolArg-46]
	_ = x[OpPushVariadicScalarArg-47]
	_ = x[OpPushVariadicStrArg-48]
	_ = x[OpPushVariadicInterfaceArg-49]
	_ = x[OpVariadicReset-50]
	_ = x[OpReturnVoid-51]
	_ = x[OpReturnFalse-52]
	_ = x[OpReturnTrue-53]
	_ = x[OpReturnStr-54]
	_ = x[OpReturnScalar-55]
	_ = x[OpReturn-56]
}

const _Op_name = "InvalidLoadScalarConstLoadStrConstMoveMove8MoveResult2NotIsNilIsNotNilIsNilInterfaceIsNotNilInterfaceLenCapStrSliceStrSliceFromStrSliceToStrIndexSliceIndexScalar8SliceIndexScalar64SliceSetScalar8SliceSetScalar64ConcatStrEqStrNotEqIntNegScalarEqScalarNotEqIntGtIntGtEqIntLtIntLtEqIntAddIntSubIntXorIntMulIntDivIntIncIntDecJumpJumpZeroJumpNotZeroCallCallRecurCallVoidCallNativeCallVoidNativePushVariadicBoolArgPushVariadicScalarArgPushVariadicStrArgPushVariadicInterfaceArgVariadicResetReturnVoidReturnFalseReturnTrueReturnStrReturnScalarReturn"

var _Op_index = [...]uint16{0, 7, 22, 34, 38, 43, 54, 57, 62, 70, 84, 101, 104, 107, 115, 127, 137, 145, 162, 180, 195, 211, 217, 222, 230, 236, 244, 255, 260, 267, 272, 279, 285, 291, 297, 303, 309, 315, 321, 325, 333, 344, 348, 357, 365, 375, 389, 408, 429, 447, 471, 484, 494, 505, 515, 524, 536, 542}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
