// Code generated by "stringer -type=Op -trimprefix=Op"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInvalid-0]
	_ = x[OpLoadScalarConst-1]
	_ = x[OpLoadStrConst-2]
	_ = x[OpMoveScalar-3]
	_ = x[OpMoveStr-4]
	_ = x[OpMoveInterface-5]
	_ = x[OpMoveResult2-6]
	_ = x[OpNot-7]
	_ = x[OpIsNil-8]
	_ = x[OpIsNotNil-9]
	_ = x[OpIsNilInterface-10]
	_ = x[OpIsNotNilInterface-11]
	_ = x[OpStrLen-12]
	_ = x[OpStrSlice-13]
	_ = x[OpStrSliceFrom-14]
	_ = x[OpStrSliceTo-15]
	_ = x[OpConcat-16]
	_ = x[OpStrEq-17]
	_ = x[OpStrNotEq-18]
	_ = x[OpIntNeg-19]
	_ = x[OpIntEq-20]
	_ = x[OpIntNotEq-21]
	_ = x[OpIntGt-22]
	_ = x[OpIntGtEq-23]
	_ = x[OpIntLt-24]
	_ = x[OpIntLtEq-25]
	_ = x[OpIntAdd-26]
	_ = x[OpIntSub-27]
	_ = x[OpIntMul-28]
	_ = x[OpIntDiv-29]
	_ = x[OpIntInc-30]
	_ = x[OpIntDec-31]
	_ = x[OpJump-32]
	_ = x[OpJumpFalse-33]
	_ = x[OpJumpTrue-34]
	_ = x[OpCall-35]
	_ = x[OpCallRecur-36]
	_ = x[OpCallVoid-37]
	_ = x[OpCallNative-38]
	_ = x[OpCallVoidNative-39]
	_ = x[OpPushVariadicBoolArg-40]
	_ = x[OpPushVariadicScalarArg-41]
	_ = x[OpPushVariadicStrArg-42]
	_ = x[OpPushVariadicInterfaceArg-43]
	_ = x[OpVariadicReset-44]
	_ = x[OpReturnVoid-45]
	_ = x[OpReturnFalse-46]
	_ = x[OpReturnTrue-47]
	_ = x[OpReturnStr-48]
	_ = x[OpReturnScalar-49]
	_ = x[OpReturnInterface-50]
}

const _Op_name = "InvalidLoadScalarConstLoadStrConstMoveScalarMoveStrMoveInterfaceMoveResult2NotIsNilIsNotNilIsNilInterfaceIsNotNilInterfaceStrLenStrSliceStrSliceFromStrSliceToConcatStrEqStrNotEqIntNegIntEqIntNotEqIntGtIntGtEqIntLtIntLtEqIntAddIntSubIntMulIntDivIntIncIntDecJumpJumpFalseJumpTrueCallCallRecurCallVoidCallNativeCallVoidNativePushVariadicBoolArgPushVariadicScalarArgPushVariadicStrArgPushVariadicInterfaceArgVariadicResetReturnVoidReturnFalseReturnTrueReturnStrReturnScalarReturnInterface"

var _Op_index = [...]uint16{0, 7, 22, 34, 44, 51, 64, 75, 78, 83, 91, 105, 122, 128, 136, 148, 158, 164, 169, 177, 183, 188, 196, 201, 208, 213, 220, 226, 232, 238, 244, 250, 256, 260, 269, 277, 281, 290, 298, 308, 322, 341, 362, 380, 404, 417, 427, 438, 448, 457, 469, 484}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
