// Code generated by "stringer -type=Op -trimprefix=Op"; DO NOT EDIT.

package bytecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInvalid-0]
	_ = x[OpLoadScalarConst-1]
	_ = x[OpLoadStrConst-2]
	_ = x[OpMoveScalar-3]
	_ = x[OpMoveStr-4]
	_ = x[OpMoveInterface-5]
	_ = x[OpMoveResult2-6]
	_ = x[OpNot-7]
	_ = x[OpIsNil-8]
	_ = x[OpIsNotNil-9]
	_ = x[OpIsNilInterface-10]
	_ = x[OpIsNotNilInterface-11]
	_ = x[OpStrLen-12]
	_ = x[OpStrSlice-13]
	_ = x[OpStrSliceFrom-14]
	_ = x[OpStrSliceTo-15]
	_ = x[OpStrIndex-16]
	_ = x[OpConcat-17]
	_ = x[OpStrEq-18]
	_ = x[OpStrNotEq-19]
	_ = x[OpIntNeg-20]
	_ = x[OpIntEq-21]
	_ = x[OpIntNotEq-22]
	_ = x[OpIntGt-23]
	_ = x[OpIntGtEq-24]
	_ = x[OpIntLt-25]
	_ = x[OpIntLtEq-26]
	_ = x[OpIntAdd-27]
	_ = x[OpIntSub-28]
	_ = x[OpIntMul-29]
	_ = x[OpIntDiv-30]
	_ = x[OpIntInc-31]
	_ = x[OpIntDec-32]
	_ = x[OpJump-33]
	_ = x[OpJumpFalse-34]
	_ = x[OpJumpTrue-35]
	_ = x[OpCall-36]
	_ = x[OpCallRecur-37]
	_ = x[OpCallVoid-38]
	_ = x[OpCallNative-39]
	_ = x[OpCallVoidNative-40]
	_ = x[OpPushVariadicBoolArg-41]
	_ = x[OpPushVariadicScalarArg-42]
	_ = x[OpPushVariadicStrArg-43]
	_ = x[OpPushVariadicInterfaceArg-44]
	_ = x[OpVariadicReset-45]
	_ = x[OpReturnVoid-46]
	_ = x[OpReturnFalse-47]
	_ = x[OpReturnTrue-48]
	_ = x[OpReturnStr-49]
	_ = x[OpReturnScalar-50]
	_ = x[OpReturnInterface-51]
}

const _Op_name = "InvalidLoadScalarConstLoadStrConstMoveScalarMoveStrMoveInterfaceMoveResult2NotIsNilIsNotNilIsNilInterfaceIsNotNilInterfaceStrLenStrSliceStrSliceFromStrSliceToStrIndexConcatStrEqStrNotEqIntNegIntEqIntNotEqIntGtIntGtEqIntLtIntLtEqIntAddIntSubIntMulIntDivIntIncIntDecJumpJumpFalseJumpTrueCallCallRecurCallVoidCallNativeCallVoidNativePushVariadicBoolArgPushVariadicScalarArgPushVariadicStrArgPushVariadicInterfaceArgVariadicResetReturnVoidReturnFalseReturnTrueReturnStrReturnScalarReturnInterface"

var _Op_index = [...]uint16{0, 7, 22, 34, 44, 51, 64, 75, 78, 83, 91, 105, 122, 128, 136, 148, 158, 166, 172, 177, 185, 191, 196, 204, 209, 216, 221, 228, 234, 240, 246, 252, 258, 264, 268, 277, 285, 289, 298, 306, 316, 330, 349, 370, 388, 412, 425, 435, 446, 456, 465, 477, 492}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
