// Code generated by "stringer -type=opcode -trimprefix=op"; DO NOT EDIT.

package quasigo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opInvalid-0]
	_ = x[opLoadScalarConst-1]
	_ = x[opLoadStrConst-2]
	_ = x[opMoveScalar-3]
	_ = x[opMoveStr-4]
	_ = x[opMoveInterface-5]
	_ = x[opMoveResult2-6]
	_ = x[opNot-7]
	_ = x[opIsNil-8]
	_ = x[opIsNotNil-9]
	_ = x[opIsNilInterface-10]
	_ = x[opIsNotNilInterface-11]
	_ = x[opStrLen-12]
	_ = x[opStrSlice-13]
	_ = x[opStrSliceFrom-14]
	_ = x[opStrSliceTo-15]
	_ = x[opConcat-16]
	_ = x[opStrEq-17]
	_ = x[opStrNotEq-18]
	_ = x[opIntEq-19]
	_ = x[opIntNotEq-20]
	_ = x[opIntGt-21]
	_ = x[opIntGtEq-22]
	_ = x[opIntLt-23]
	_ = x[opIntLtEq-24]
	_ = x[opIntAdd-25]
	_ = x[opIntSub-26]
	_ = x[opIntMul-27]
	_ = x[opIntDiv-28]
	_ = x[opIntInc-29]
	_ = x[opIntDec-30]
	_ = x[opJump-31]
	_ = x[opJumpFalse-32]
	_ = x[opJumpTrue-33]
	_ = x[opCall-34]
	_ = x[opCallRecur-35]
	_ = x[opCallNative-36]
	_ = x[opCallVoidNative-37]
	_ = x[opPushVariadicBoolArg-38]
	_ = x[opPushVariadicScalarArg-39]
	_ = x[opPushVariadicStrArg-40]
	_ = x[opPushVariadicInterfaceArg-41]
	_ = x[opVariadicReset-42]
	_ = x[opReturnVoid-43]
	_ = x[opReturnFalse-44]
	_ = x[opReturnTrue-45]
	_ = x[opReturnStr-46]
	_ = x[opReturnScalar-47]
	_ = x[opReturnInterface-48]
}

const _opcode_name = "InvalidLoadScalarConstLoadStrConstMoveScalarMoveStrMoveInterfaceMoveResult2NotIsNilIsNotNilIsNilInterfaceIsNotNilInterfaceStrLenStrSliceStrSliceFromStrSliceToConcatStrEqStrNotEqIntEqIntNotEqIntGtIntGtEqIntLtIntLtEqIntAddIntSubIntMulIntDivIntIncIntDecJumpJumpFalseJumpTrueCallCallRecurCallNativeCallVoidNativePushVariadicBoolArgPushVariadicScalarArgPushVariadicStrArgPushVariadicInterfaceArgVariadicResetReturnVoidReturnFalseReturnTrueReturnStrReturnScalarReturnInterface"

var _opcode_index = [...]uint16{0, 7, 22, 34, 44, 51, 64, 75, 78, 83, 91, 105, 122, 128, 136, 148, 158, 164, 169, 177, 182, 190, 195, 202, 207, 214, 220, 226, 232, 238, 244, 250, 254, 263, 271, 275, 284, 294, 308, 327, 348, 366, 390, 403, 413, 424, 434, 443, 455, 470}

func (i opcode) String() string {
	if i >= opcode(len(_opcode_index)-1) {
		return "opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
