// Code generated by "stringer -type=PseudoOp -trimprefix=Op"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpUnset-0]
	_ = x[OpLabel-1]
	_ = x[OpVarKill-2]
}

const _PseudoOp_name = "UnsetLabelVarKill"

var _PseudoOp_index = [...]uint8{0, 5, 10, 17}

func (i PseudoOp) String() string {
	if i >= PseudoOp(len(_PseudoOp_index)-1) {
		return "PseudoOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PseudoOp_name[_PseudoOp_index[i]:_PseudoOp_index[i+1]]
}
