// Code generated by "stringer -type=SlotKind -trimprefix=Slot"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SlotCallArg-0]
	_ = x[SlotParam-1]
	_ = x[SlotTemp-2]
	_ = x[SlotUniq-3]
	_ = x[SlotDiscard-4]
}

const _SlotKind_name = "CallArgParamTempUniqDiscard"

var _SlotKind_index = [...]uint8{0, 7, 12, 16, 20, 27}

func (i SlotKind) String() string {
	if i >= SlotKind(len(_SlotKind_index)-1) {
		return "SlotKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SlotKind_name[_SlotKind_index[i]:_SlotKind_index[i+1]]
}
